# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.full_version)
np.show_config()

1.12.1
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/masa/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/masa/anaconda/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/masa/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/masa/anaconda/include']
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/masa/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/masa/anaconda/include']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/masa/anaconda/lib']
    define_macros = [('SCIPY_MKL_H'

#### 3. Create a null vector of size 10 (★☆☆)

In [18]:
nv = np.zeros(10)
print(nv)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [22]:
nv.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [30]:
 np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [32]:
a = np.zeros(10)
a[4] = 1
print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [36]:
b = np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [37]:
b[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [38]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [61]:
c = [1,2,0,0,4,0]
np.nonzero(c)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [62]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [65]:
np.random.rand(3,3,3)

array([[[ 0.41357742,  0.4518072 ,  0.98180789],
        [ 0.97488478,  0.6424815 ,  0.46418595],
        [ 0.69002876,  0.7591951 ,  0.54900017]],

       [[ 0.65930825,  0.28214961,  0.34119842],
        [ 0.77244962,  0.17798912,  0.26716386],
        [ 0.30084211,  0.01243349,  0.43575733]],

       [[ 0.79757826,  0.57579284,  0.05690473],
        [ 0.618869  ,  0.91419356,  0.03688423],
        [ 0.78949793,  0.18389871,  0.36300037]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [77]:
d = np.random.rand(10,10)
print("maximum: ",d.max())
print("minimum: ",d.min())

maximum:  0.970111574337
minimum:  0.0144580688562


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [82]:
e = np.random.rand(30)
e.mean()

0.56346328147375691

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [91]:
f = np.ones((5,5))
f[1:-1,1:-1]=0
print(f)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [101]:
g = np.ones((5,5))
g = np.pad(g, pad_width=3, mode='constant', constant_values=0)
print(g)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [104]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [108]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
Z = np.eye(2)
print(np.tile(Z,(4,4)))

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
Z = np.random.rand(5,5)
Zmax=Z.max()
Zmin=Z.min()
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[ 0.06280738  0.91186909  0.4964786   0.02682036  0.21598503]
 [ 0.14268891  0.86053418  0.55578886  0.86461911  0.00675169]
 [ 0.51105876  0.02881279  0.          0.14447427  0.92276698]
 [ 0.49462437  0.54636585  0.57251091  1.          0.99967384]
 [ 0.78559714  0.9028088   0.11634977  0.20983482  0.06744988]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
a = np.ones((5,3))
b = np.ones((3,2))
Z = np.dot(a,b)
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [37]:
Z = np.arange(10)
Z[(3<=Z)&(Z<=9)]*=-1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8 -9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [38]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [47]:
print(sum(range(5)))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
#Z**Z
Z = np.ones((3,3),dtype=int)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[False False False]
 [False False False]
 [False False False]]
[[ 0.+1.j  0.+1.j  0.+1.j]
 [ 0.+1.j  0.+1.j  0.+1.j]
 [ 0.+1.j  0.+1.j  0.+1.j]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/Users/masa/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/masa/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [61]:
np.info(np.random.uniform)

uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than high.  The default value is 1.0.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``low`` and ``high`` are both scalars.
    Otherwise, ``np.broadcast(low, high).size`` samples are drawn.

Returns
-------
out : ndarray or s

In [62]:
np.info(np.ceil)

ceil(x[, out])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.

Returns
-------
y : ndarray or scalar
    The ceiling of each element in `x`, with `float` dtype.

See Also
--------
floor, trunc, rint

Examples
--------
>>> a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
>>> np.ceil(a)
array([-1., -1., -0.,  1.,  2.,  2.,  2.])


In [74]:
np.info(np.copysign)

copysign(x1, x2[, out])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, optional
    Array into which the output is placed. Its type is preserved and it
    must be of the right shape to hold the output. See doc.ufuncs.

Returns
-------
out : array_like
    The values of `x1` with the sign of `x2`.

Examples
--------
>>> np.copysign(1.3, -1)
-1.3
>>> 1/np.copysign(0, 1)
inf
>>> 1/np.copysign(0, -1)
-inf

>>> np.copysign([-1, 0, 1], -1.1)
array([-1., -0., -1.])
>>> np.copysign([-1, 0, 1], np.arange(3)-1)
array([-1.,  0.,  1.])


In [80]:
Z = np.random.uniform(-10,+10,10)
print(Z)

[ 7.81638729  7.57204923  7.4718705   8.96805645 -3.17017605 -8.07050241
 -8.39205065  0.60921748 -3.16606944 -7.72369482]


In [81]:
Y = np.ceil(np.abs(Z))
print(Y)

[ 8.  8.  8.  9.  4.  9.  9.  1.  4.  8.]


In [83]:
print (np.copysign(Y, Z))

[ 8.  8.  8.  9. -4. -9. -9.  1. -4. -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [86]:
np.info(np.intersect1d)

 intersect1d(ar1, ar2, assume_unique=False)

Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  Default is False.

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.

See Also
--------
numpy.lib.arraysetops : Module with a number of other functions for
                        performing set operations on arrays.

Examples
--------
>>> np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
array([1, 3])

To intersect more than two arrays, use functools.reduce:

>>> from functools import reduce
>>> reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
array([3])


In [87]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[1 2 3 2 8 0 7 7 3 3]
[5 0 3 1 4 1 0 7 2 5]
[0 1 2 3 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [91]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

[ inf]


In [92]:
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
print(Z)

[ inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [93]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [95]:
print(np.sqrt(-1))

nan


In [94]:
print(np.emath.sqrt(-1))

1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [96]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [97]:
print(yesterday)
print(today)
print(tomorrow)

2017-12-30
2017-12-31
2018-01-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [98]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [99]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [102]:
Z = np.random.uniform(0,10,10)
print(Z)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 6.31609507  9.98871099  7.36827279  1.4271772   0.61478579  5.4081216
  2.95076413  2.24265553  8.47345489  3.01977771]
[ 6.  9.  7.  1.  0.  5.  2.  2.  8.  3.]
[ 6.  9.  7.  1.  0.  5.  2.  2.  8.  3.]
[ 6.  9.  7.  1.  0.  5.  2.  2.  8.  3.]
[6 9 7 1 0 5 2 2 8 3]
[ 6.  9.  7.  1.  0.  5.  2.  2.  8.  3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [106]:
Z = np.zeros((5,5))
Z = Z + np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [109]:
def generate():
    for x in range(10):
        yield x

In [113]:
np.info(np.fromiter)

fromiter(iterable, dtype, count=-1)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
>>> iterable = (x*x for x in range(5))
>>> np.fromiter(iterable, np.float)
array([  0.,   1.,   4.,   9.,  16.])


In [111]:
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [114]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional
    The type of the ou

In [119]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [121]:
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)

[ 0.62436128  0.5810116   0.5389052   0.94605647  0.7541047   0.67404293
  0.65916902  0.51226302  0.55490343  0.862518  ]
[ 0.51226302  0.5389052   0.55490343  0.5810116   0.62436128  0.65916902
  0.67404293  0.7541047   0.862518    0.94605647]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [123]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [126]:
np.info(np.random.randint)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int'

In [180]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 0 0 1]
[1 0 0 0 1]
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [185]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [189]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.74555853  0.65116371  0.9010133   0.74976425  0.84095324  1.04256121
  0.74502725  0.60539513  1.1166143   0.49066632]
[ 0.21371817  1.56502026  0.06932397  1.37263613  0.4939199   0.4141591
  1.46777686  1.27852598  1.01709018  0.57589558]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [191]:
Z = np.random.rand(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[ 0.91429853  0.87997084  0.81982443  0.23513772  0.9410269   0.32617834
  0.90784981  0.61745315  0.13634883  0.01307488]
[ 0.91429853  0.87997084  0.81982443  0.23513772  0.          0.32617834
  0.90784981  0.61745315  0.13634883  0.01307488]


In [194]:
np.info(argmax)

 argmax(a, axis=None, out=None)

Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed.

See Also
--------
ndarray.argmax, argmin
amax : The maximum value along a given axis.
unravel_index : Convert a flat index into an index tuple.

Notes
-----
In case of multiple occurrences of the maximum values, the indices
corresponding to the first occurrence are returned.

Examples
--------
>>> a = np.arange(6).reshape(2,3)
>>> a
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.argmax(a)
5
>>> np.argmax(a, axis=0)
array([1, 1, 1])
>>> 

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [195]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


In [196]:
np.info(np.meshgrid)

 meshgrid(*xi, **kwargs)

Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of
N-D scalar/vector fields over N-D grids, given
one-dimensional coordinate arrays x1, x2,..., xn.

.. versionchanged:: 1.9
   1-D and 0-D cases are allowed.

Parameters
----------
x1, x2,..., xn : array_like
    1-D arrays representing the coordinates of a grid.
indexing : {'xy', 'ij'}, optional
    Cartesian ('xy', default) or matrix ('ij') indexing of output.
    See Notes for more details.

    .. versionadded:: 1.7.0
sparse : bool, optional
    If True a sparse grid is returned in order to conserve memory.
    Default is False.

    .. versionadded:: 1.7.0
copy : bool, optional
    If False, a view into the original arrays are returned in order to
    conserve memory.  Default is True.  Please note that
    ``sparse=False, copy=False`` will likely return non-contiguous
    arrays.  Furthermore, more than one element of a broadcast array
    may refe

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [197]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


In [200]:
print(X)
print(Y)
print(np.subtract.outer(X, Y))

[0 1 2 3 4 5 6 7]
[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5]
[[-0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5]
 [ 0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5]
 [ 1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5]
 [ 2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5]
 [ 3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5]
 [ 4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5]
 [ 5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5]
 [ 6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5]]


In [201]:
np.info(np.linalg.det)

 det(a)

Compute the determinant of an array.

Parameters
----------
a : (..., M, M) array_like
    Input array to compute determinants for.

Returns
-------
det : (...) array_like
    Determinant of `a`.

See Also
--------
slogdet : Another way to representing the determinant, more suitable
  for large matrices where underflow/overflow may occur.

Notes
-----

.. versionadded:: 1.8.0

Broadcasting rules apply, see the `numpy.linalg` documentation for
details.

The determinant is computed via LU factorization using the LAPACK
routine z/dgetrf.

Examples
--------
The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:

>>> a = np.array([[1, 2], [3, 4]])
>>> np.linalg.det(a)
-2.0

Computing determinants for a stack of matrices:

>>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
>>> a.shape
(3, 2, 2)
>>> np.linalg.det(a)
array([-2., -3., -8.])


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [202]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆)

In [203]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [204]:
np.info(np.set_printoptions)

 set_printoptions(precision=None, threshold=None, edgeitems=None,
                  linewidth=None, suppress=None, nanstr=None, infstr=None,
                  formatter=None)

Set printing options.

These options determine the way floating point numbers, arrays and
other NumPy objects are displayed.

Parameters
----------
precision : int, optional
    Number of digits of precision for floating point output (default 8).
threshold : int, optional
    Total number of array elements which trigger summarization
    rather than full repr (default 1000).
edgeitems : int, optional
    Number of array items in summary at beginning and end of
    each dimension (default 3).
linewidth : int, optional
    The number of characters per line for the purpose of inserting
    line breaks (default 75).
suppress : bool, optional
    Whether or not suppress printing of small floating point values
    using scientific notation (default False).
nanstr : str, optional
    String representation of floating po

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [207]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
print(v)

36
35.67005072185025


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [208]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [210]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[ 0.          0.56479587  0.61248436  0.16068459  0.25978581  0.63298448
   0.89717025  0.62860658  0.89306033  0.76022908]
 [ 0.56479587  0.          0.68868793  0.50021936  0.47192176  0.43645144
   0.54932082  0.56285933  0.35499393  0.19575402]
 [ 0.61248436  0.68868793  0.          0.72639115  0.79785167  0.31469482
   1.22720301  0.16810805  1.01383152  0.81994706]
 [ 0.16068459  0.50021936  0.72639115  0.          0.09950576  0.68175081
   0.7516361   0.71059549  0.79379653  0.68767381]
 [ 0.25978581  0.47192176  0.79785167  0.09950576  0.          0.71822344
   0.65969476  0.76501624  0.73337764  0.64762925]
 [ 0.63298448  0.43645144  0.31469482  0.68175081  0.71822344  0.
   0.9850174   0.1506778   0.72156904  0.52678799]
 [ 0.89717025  0.54932082  1.22720301  0.7516361   0.65969476  0.9850174
   0.          1.11113186  0.38539669  0.51258948]
 [ 0.62860658  0.56285933  0.16810805  0.71059549  0.76501624  0.1506778
   1.11113186  0.          0.86722398  0.672234  ]
 [ 0.89306

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [212]:
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [213]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

TypeError: must be str or None, not bytes

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [214]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [215]:
np.info(np.ndenumerate)

 ndenumerate()

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


Methods:

  next  --  Standard iterator method, returns the index tuple and array value.


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [216]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [217]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  1.  0.  0.  0.]]


In [218]:
np.info(np.random.choice)

choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

        .. versionadded:: 1.7.0

Parameters
-----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if a was np.arange(n)
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given the sample assumes a uniform distribution over all
    entries in a.

Returns
--------
samples : 1-D ndarray, shape (size,)
    The generated random samples

Raises
-------
ValueError
    If a is an int and less than zero, if a or p are not 1-dimensional,
    if a is an array-like of size 0, if 

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [219]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[  3.48659939e-01   3.40451470e-01  -1.76392040e-01  -3.02640833e-01
    2.16743504e-01   2.50842558e-01  -4.31194207e-01   9.45305751e-02
   -5.43298072e-01   2.02297105e-01]
 [  3.25022985e-01   2.06892160e-01   3.75386899e-02  -1.45369677e-01
    3.04879403e-01   1.07593347e-01  -3.18862660e-02   2.98534498e-01
   -4.91046242e-01  -6.12158899e-01]
 [  7.64998663e-02  -1.23873150e-01  -8.53370536e-02  -2.62471735e-01
    1.15401713e-01   1.35801710e-01  -5.24204349e-02   2.11405212e-04
    2.67533235e-01  -7.13455562e-02]
 [  1.79102971e-01   4.35580801e-01  -1.59375272e-01   3.53580361e-01
    1.43575155e-01  -3.49133350e-01   2.45693619e-02  -4.44268553e-01
   -2.84434252e-01   1.00802778e-01]
 [ -7.23147299e-02  -3.72073612e-01  -4.41384916e-01   3.25332665e-01
    3.74801833e-01  -3.30275095e-01  -4.11474437e-01   4.82581910e-01
   -1.73971022e-02   4.62203484e-01]]


#### 59. How to sort an array by the nth column? (★★☆)

In [224]:
Z = np.random.randint(0,10,(5,5))
print(Z)
print(Z[Z[:,4].argsort()])

[[6 5 7 5 7]
 [3 3 0 4 8]
 [3 0 7 1 4]
 [3 1 0 8 1]
 [1 2 5 4 7]]
[[3 1 0 8 1]
 [3 0 7 1 4]
 [6 5 7 5 7]
 [1 2 5 4 7]
 [3 3 0 4 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [236]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

Z = np.random.randint(1,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 1 2 2 0 2 1 1 2 2]
 [2 0 2 2 0 1 1 0 1 2]
 [2 0 1 1 0 2 0 2 2 2]]
True
[[1 2 1 1 1 2 2 1 2 1]
 [1 1 2 2 2 2 1 1 2 1]
 [1 1 2 1 1 1 1 1 1 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [238]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[ 0.05233249  0.46446873  0.12571995  0.339144    0.18642851  0.91037859
  0.75871647  0.79793765  0.38895143  0.48403297]
0.484032972679


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [239]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [241]:
np.info(np.nditer)

 nditer()

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.
flags : sequence of str, optional
    Flags to control the behavior of the iterator.

      * "buffered" enables buffering when required.
      * "c_index" causes a C-order index to be tracked.
      * "f_index" causes a Fortran-order index to be tracked.
      * "multi_index" causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * "common_dtype" causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * "delay_bufalloc" delays allocation of the buffers until
        a reset() call is made. Allows "allocate" operands to
        be initialized before their values are copied into the buffers.
      * "e

#### 63. Create an array class that has a name attribute (★★☆)

In [242]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [255]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),30)
print(I)
np.add.at(Z, I, 1)
print(Z)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[2 6 7 6 1 0 7 0 9 2 1 7 5 0 0 0 0 6 3 5 3 1 1 7 7 4 4 0 0 1]
[ 9.  6.  3.  3.  3.  3.  4.  6.  1.  2.]


In [251]:
np.info(np.add.at)

at(a, indices, b=None)

Performs unbuffered in place operation on operand 'a' for elements
specified by 'indices'. For addition ufunc, this method is equivalent to
`a[indices] += b`, except that results are accumulated for elements that
are indexed more than once. For example, `a[[0,0]] += 1` will only
increment the first element once because of buffering, whereas
`add.at(a, [0,0], 1)` will increment the first element twice.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    The array to perform in place operation on.
indices : array_like or tuple
    Array like index object or slice object for indexing into first
    operand. If first operand has multiple dimensions, indices can be a
    tuple of array like index objects or slice objects.
b : array_like
    Second operand for ufuncs requiring two operands. Operand must be
    broadcastable over first operand after indexing or slicing.

Examples
--------
Set items 0 and 1 to their negative values:

>>> a = np.array([1, 

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [256]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [257]:
np.info(np.bincount)

bincount(x, weights=None, minlength=None)

Count number of occurrences of each value in array of non-negative ints.

The number of bins (of size 1) is one larger than the largest value in
`x`. If `minlength` is specified, there will be at least this number
of bins in the output array (though it will be longer if necessary,
depending on the contents of `x`).
Each bin gives the number of occurrences of its index value in `x`.
If `weights` is specified the input array is weighted by it, i.e. if a
value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
of ``out[n] += 1``.

Parameters
----------
x : array_like, 1 dimension, nonnegative ints
    Input array.
weights : array_like, optional
    Weights, array of the same shape as `x`.
minlength : int, optional
    A minimum number of bins for the output array.

    .. versionadded:: 1.6.0

Returns
-------
out : ndarray of ints
    The result of binning the input array.
    The length of `out` is equal to ``np.amax(x)+1``.

Rais

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [262]:
w,h = 4,4
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
print(I)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(F)
n = len(np.unique(F))
print(n)

[[[0 0 0]
  [0 0 0]
  [1 1 0]
  [1 1 0]]

 [[0 0 0]
  [0 1 1]
  [0 0 1]
  [1 0 1]]

 [[0 1 1]
  [1 0 0]
  [1 0 0]
  [1 1 1]]

 [[0 1 1]
  [0 0 1]
  [0 1 0]
  [1 0 0]]]
[[    0     0 65792 65792]
 [    0   257     1 65537]
 [  257 65536 65536 65793]
 [  257     1   256 65536]]
8


In [263]:
np.info(np.unique)

 unique(ar, return_index=False, return_inverse=False, return_counts=False)

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements: the indices of the input array
that give the unique values, the indices of the unique array that
reconstruct the input array, and the number of times each unique value
comes up in the input array.

Parameters
----------
ar : array_like
    Input array. This will be flattened if it is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` that result in the unique
    array.
return_inverse : bool, optional
    If True, also return the indices of the unique array that can be used
    to reconstruct `ar`.
return_counts : bool, optional
    If True, also return the number of times each unique value comes up
    in `ar`.

    .. versionadded:: 1.9.0

Returns
-------
unique : ndarray
    The sorted unique values.
unique_indices

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [271]:
A = np.random.randint(0,2,(2,2,2,2))
print(A)
sum = A.sum(axis=(-2,-1))
print(sum)

[[[[0 0]
   [1 0]]

  [[1 1]
   [0 0]]]


 [[[0 0]
   [1 0]]

  [[0 0]
   [1 1]]]]
[[1 2]
 [1 2]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [277]:
D = np.random.uniform(0,1,5)
print(D)
S = np.random.randint(0,10,5)
print(S)
D_sums = np.bincount(S, weights=D)
print(D_sums)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[ 0.52839448  0.05406228  0.59112916  0.88186046  0.50478615]
[4 2 5 9 1]
[ 0.          0.50478615  0.05406228  0.          0.52839448  0.59112916
  0.          0.          0.          0.88186046]
[        nan  0.50478615  0.05406228         nan  0.52839448  0.59112916
         nan         nan         nan  0.88186046]


#### 69. How to get the diagonal of a dot product? (★★★)

In [278]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([ 0.60028073,  1.00086797,  0.73685424,  1.03903065,  1.39764464])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [279]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [280]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [283]:
A = np.arange(9).reshape(3,3)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [284]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8,  9) ( 8, 68) ( 9, 19) ( 9, 58) ( 9, 68) ( 9, 80) ( 9, 84) (13, 58)
 (13, 89) (14, 54) (14, 90) (17, 53) (17, 96) (19, 58) (26, 44) (26, 54)
 (41, 63) (41, 92) (44, 54) (45, 73) (45, 80) (53, 96) (54, 90) (58, 89)
 (63, 92) (73, 80) (76, 79) (76, 98) (79, 98) (80, 84)]


In [285]:
np.info(np.roll)

 roll(a, shift, axis=None)

Roll array elements along a given axis.

Elements that roll beyond the last position are re-introduced at
the first.

Parameters
----------
a : array_like
    Input array.
shift : int or tuple of ints
    The number of places by which elements are shifted.  If a tuple,
    then `axis` must be a tuple of the same size, and each of the
    given axes is shifted by the corresponding number.  If an int
    while `axis` is a tuple of ints, then the same value is used for
    all given axes.
axis : int or tuple of ints, optional
    Axis or axes along which elements are shifted.  By default, the
    array is flattened before shifting, after which the original
    shape is restored.

Returns
-------
res : ndarray
    Output array, with the same shape as `a`.

See Also
--------
rollaxis : Roll the specified axis backwards, until it lies in a
           given position.

Notes
-----
.. versionadded:: 1.12.0

Supports rolling over multiple dimensions simultaneously.

E

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [287]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


In [288]:
np.info(np.repeat)

 repeat(a, repeats, axis=None)

Repeat elements of an array.

Parameters
----------
a : array_like
    Input array.
repeats : int or array of ints
    The number of repetitions for each element.  `repeats` is broadcasted
    to fit the shape of the given axis.
axis : int, optional
    The axis along which to repeat values.  By default, use the
    flattened input array, and return a flat output array.

Returns
-------
repeated_array : ndarray
    Output array which has the same shape as `a`, except along
    the given axis.

See Also
--------
tile : Tile an array.

Examples
--------
>>> np.repeat(3, 4)
array([3, 3, 3, 3])
>>> x = np.array([[1,2],[3,4]])
>>> np.repeat(x, 2)
array([1, 1, 2, 2, 3, 3, 4, 4])
>>> np.repeat(x, 3, axis=1)
array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])
>>> np.repeat(x, [1, 2], axis=0)
array([[1, 2],
       [3, 4],
       [3, 4]])


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [298]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(Z)
print(moving_average(Z, n=11))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [299]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [305]:
Z = np.random.randint(0,2,10)
print(Z)
np.logical_not(Z, out=Z)
print(Z)

Z = np.random.uniform(-1.0,1.0,10)
print(Z)
np.negative(Z, out=Z)
print(Z)

[1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 1 1 1 0 1 1]
[ 0.38830094 -0.77038289  0.82000621 -0.55854973  0.72728509 -0.11033463
  0.18065046  0.57492025  0.03490564 -0.5617404 ]
[-0.38830094  0.77038289 -0.82000621  0.55854973 -0.72728509  0.11033463
 -0.18065046 -0.57492025 -0.03490564  0.5617404 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [306]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 15.63411598   1.87676921  11.77357016   8.0493695    2.98565073
   4.86516854   9.32054506   5.25232289  16.08722216   2.01972751]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [307]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 11.0249912    4.38369721   0.95422138   2.83096323   4.96106998
    7.08429687   8.63492255   6.77287348  14.37947392   3.25861694]
 [  1.13452667   1.25632414  11.21403283   2.59765475   9.64046706
    4.57624104   1.91622774   6.27806621   0.17178677   3.35774781]
 [  4.76565579   3.25969353   5.3090482    0.25906607   2.25182235
    1.05105361   3.11208569   6.09415676   7.44807793   0.37063037]
 [  1.81596038  13.69466146   8.24789198   8.38490091   1.19862404
    2.48641735   1.55403173   3.79425858  12.80844709  10.69736945]
 [  2.45707828   3.83689044   7.6179275    2.00200722   4.29255406
    1.23693764   0.88850138   4.97835333   5.6719222    0.3626318 ]
 [ 13.2238523    9.94013108   3.16044566   0.77674214  10.71929343
    8.87688376   9.6036723    2.50692348  20.87545375   9.77509645]
 [  4.3337147   13.1747152   14.40075517  11.77625702   5.52285518
    8.45096541   7.09008613   4.97104537   6.45825278   8.48287926]
 [  9.13715119   3.79838938   0.9350906    2.04882206  

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [308]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 4 4 1 6 2 6 5 1 2]
 [1 8 2 9 6 4 5 5 5 9]
 [6 7 5 9 8 0 3 6 7 5]
 [0 8 9 1 6 6 1 4 4 0]
 [8 5 3 0 0 4 1 4 9 3]
 [5 4 6 1 1 8 7 7 9 8]
 [8 9 0 9 2 7 3 6 8 0]
 [7 8 4 1 3 7 2 3 2 7]
 [9 9 4 8 1 1 2 2 5 3]
 [0 6 7 5 8 2 2 2 9 6]]
[[0 0 0 0 0]
 [0 2 4 4 1]
 [0 1 8 2 9]
 [0 6 7 5 9]
 [0 0 8 9 1]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [309]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [310]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [311]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [312]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 4]
   [2 2 1]
   [4 2 2]]

  [[4 4 2]
   [2 1 4]
   [2 2 4]]

  [[4 2 0]
   [1 4 3]
   [2 4 1]]

  [[2 0 1]
   [4 3 4]
   [4 1 4]]

  [[0 1 1]
   [3 4 0]
   [1 4 4]]

  [[1 1 1]
   [4 0 2]
   [4 4 2]]

  [[1 1 4]
   [0 2 3]
   [4 2 0]]

  [[1 4 0]
   [2 3 3]
   [2 0 3]]]


 [[[2 2 1]
   [4 2 2]
   [4 3 0]]

  [[2 1 4]
   [2 2 4]
   [3 0 1]]

  [[1 4 3]
   [2 4 1]
   [0 1 0]]

  [[4 3 4]
   [4 1 4]
   [1 0 0]]

  [[3 4 0]
   [1 4 4]
   [0 0 0]]

  [[4 0 2]
   [4 4 2]
   [0 0 1]]

  [[0 2 3]
   [4 2 0]
   [0 1 0]]

  [[2 3 3]
   [2 0 3]
   [1 0 1]]]


 [[[4 2 2]
   [4 3 0]
   [0 2 1]]

  [[2 2 4]
   [3 0 1]
   [2 1 4]]

  [[2 4 1]
   [0 1 0]
   [1 4 3]]

  [[4 1 4]
   [1 0 0]
   [4 3 4]]

  [[1 4 4]
   [0 0 0]
   [3 4 0]]

  [[4 4 2]
   [0 0 1]
   [4 0 1]]

  [[4 2 0]
   [0 1 0]
   [0 1 4]]

  [[2 0 3]
   [1 0 1]
   [1 4 2]]]


 [[[4 3 0]
   [0 2 1]
   [2 2 4]]

  [[3 0 1]
   [2 1 4]
   [2 4 0]]

  [[0 1 0]
   [1 4 3]
   [4 0 0]]

  [[1 0 0]
   [4 3 4]
   [0 0 3]]

  [[0 0 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [313]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  2 11 13  6]
 [ 2  1  5  8  8]
 [11  5  6 42 11]
 [13  8 42  1  4]
 [ 6  8 11  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [314]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [315]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [316]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  1 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  1 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [320]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [321]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [322]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello',  2.5, 3) (b'World',  3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [324]:
x = np.random.rand(100)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

The slowest run took 5.46 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.64 µs per loop
The slowest run took 6.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.34 µs per loop
The slowest run took 3412.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.51 µs per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [325]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [327]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 4 1]
 [3 3 0]
 [3 0 1]
 [1 1 3]
 [3 0 0]
 [1 0 1]
 [1 3 0]
 [0 3 2]
 [0 4 2]
 [2 1 4]]
[[2 4 1]
 [3 3 0]
 [3 0 1]
 [1 1 3]
 [3 0 0]
 [1 0 1]
 [1 3 0]
 [0 3 2]
 [0 4 2]
 [2 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [328]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [329]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [330]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[ 0.27194697,  0.24179344,  0.41759344,  0.48284461,  0.6838292 ,
         0.2467282 ,  0.15527585,  0.21018774,  0.21081662,  0.25380466],
       [ 0.30662913,  0.27263004,  0.4708503 ,  0.54442314,  0.77103986,
         0.27819414,  0.17507861,  0.23699357,  0.23770265,  0.28617309],
       [ 0.30880071,  0.27456084,  0.47418493,  0.54827882,  0.77650046,
         0.28016435,  0.17631854,  0.23867199,  0.23938609,  0.2881998 ],
       [ 0.3081755 ,  0.27400494,  0.47322486,  0.54716874,  0.77492831,
         0.27959711,  0.17596156,  0.23818876,  0.23890142,  0.28761629],
       [ 0.24277876,  0.21585941,  0.37280363,  0.43105617,  0.61048375,
         0.22026488,  0.13862143,  0.18764364,  0.18820507,  0.22658235],
       [ 0.10143742,  0.09019002,  0.1557642 ,  0.18010318,  0.25507132,
         0.09203071,  0.05791858,  0.07840096,  0.07863553,  0.09467026],
       [ 0.03688256,  0.03279302,  0.05663573,  0.06548537,  0.09274372,
         0.03346229,  0.02105915,  0.02850652

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [331]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [332]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[ 2.  0.  1.  1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [333]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.141059  0.238707]
